
services:
  db:
    image: postgres:15
    container_name: spendapp_db
    restart: always
    environment:
      POSTGRES_DB: spendapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data # Persist database data

  pgadmin:
    image: dpage/pgadmin4
    container_name: spendapp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: spendapp_backend
    restart: always
    ports:
      - "5000:5000"  # Expose your backend app
    environment:
      FLASK_APP: app.py  # Flask entry point
      FLASK_ENV: development
    depends_on:
      - db
