"""Increase hashed_password column length

Revision ID: 598fa1f6db59
Revises: 5e59497f6dae
Create Date: 2025-03-25 23:32:20.550990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598fa1f6db59'
down_revision = '5e59497f6dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ### 